apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineswepttd
  namespace: monthly-challenge
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: mineswepttd
  template:
    metadata:
      labels:
        app: mineswepttd
    spec:
      containers:
      - name: mineswepttd
        image: pard68/mineswepttd
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 5
